### ISSUE TITLE
2 new Lua errors on 4.9941a

### ISSUE THREAD

**Issue by Ulidan** [stpain/guildbook#106]
1:
    2x Guildbook\Core.lua:3382: bad argument #3 to 'format' (string expected, got nil)
    [string "=[C]"]: in function `format'
    [string "@Guildbook\Core.lua"]:3382: in function `Init'
    [string "@Guildbook\Core.lua"]:6160: in function <Guildbook\Core.lua:6155>
    
    Locals:
    (*temporary) = "Load time: %s > current version; %s"
    (*temporary) = "20:39:39"
    (*temporary) = nil
    (*temporary) = "string expected, got nil"

2:
    2x FrameXML\StaticPopup.lua:4573: bad argument #2 to 'SetFormattedText' (string expected, got nil)
    [string "=[C]"]: in function `SetFormattedText'
    [string "@FrameXML\StaticPopup.lua"]:4573: in function <FrameXML\StaticPopup.lua:4424>
    [string "=[C]"]: ?
    [string "=[C]"]: ?
    [string "=[C]"]: in function `StaticPopup_Show'
    [string "@Guildbook\Core.lua"]:4006: in function `Load'
    [string "@Guildbook\Core.lua"]:3770: in function <Guildbook\Core.lua:3755>
    [string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>
    
    Locals:
    (*temporary) = StaticPopup3Text {
     0 = <userdata>
    }
    (*temporary) = "Guildbook Version: %s
    
    %s"
    (*temporary) = nil
    (*temporary) = "|cFFFF0000IMPORTANT!|r
    This is the last big update before |cff45b6feWrath of the Lich King Classic|r
	    
    The addon is being reworked for a better compatibility with the next classic expansion.
    This expansion brings new features such as dual spec and glyphs and the current version of the addon isn't compatible with these changes from Blizzard.
	    
    The current version will remain available via curse as is and if/when Blizzard make any announcements for new Classic SoM or TBC SoM servers, either the new version can be backported to work with those servers or the older version will receive maintenance.
	    
    Check the Discord server for more informations.
    "
    (*temporary) = "string expected, got nil"

**Comment by Belrand** [comment]
I think I see, what's going on, I did an oopsie, my bad.

Thanks for the report I'll try to fix it ASAP

**Comment by Belrand** [comment]
The issue came from a wrong label in the "Version" of the addon within the .toc file, it should be resolved.

Update as been send to curse and is waiting for approval, if you don't want to download it again, you can simply open the file Guildbook-XXX.toc (where XXX correspond that version of the game you're running Classic or BCC) with a text editor and change the version from `4.9941a` to `4.99411`.

Sorry again for the mistake.
