### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by MurderOnMyMind7** [stpain/guildbook#107]
Lua Error 1/3:
Message: Interface\AddOns\Guildbook\Core.lua:3382: bad argument #3 to 'format' (string expected, got nil)
Time: Sat Jul 30 14:32:32 2022
Count: 1
Stack: Interface\AddOns\Guildbook\Core.lua:3382: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\Guildbook\Core.lua"]:3382: in function `Init'
[string "@Interface\AddOns\Guildbook\Core.lua"]:6160: in function <Interface\AddOns\Guildbook\Core.lua:6155>

Locals: (*temporary) = "Load time: %s > current version; %s"
(*temporary) = "14:32:32"
(*temporary) = nil
(*temporary) = "string expected, got nil"

Lua Error 2/3:
Message: Interface\FrameXML\StaticPopup.lua:4573: bad argument #2 to 'SetFormattedText' (string expected, got nil)
Time: Sat Jul 30 14:32:41 2022
Count: 1
Stack: Interface\FrameXML\StaticPopup.lua:4573: bad argument #2 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\FrameXML\StaticPopup.lua"]:4573: in function <Interface\FrameXML\StaticPopup.lua:4424>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `StaticPopup_Show'
[string "@Interface\AddOns\Guildbook\Core.lua"]:4006: in function `Load'
[string "@Interface\AddOns\Guildbook\Core.lua"]:3770: in function <Interface\AddOns\Guildbook\Core.lua:3755>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: (*temporary) = StaticPopup3Text {
 0 = <userdata>
}
(*temporary) = "Guildbook Version: %s

%s"
(*temporary) = nil
(*temporary) = "IMPORTANT!
This is the last big update before Wrath of the Lich King Classic
	
The addon is being reworked for a better compatibility with the next classic expansion.
This expansion brings new features such as dual spec and glyphs and the current version of the addon isn't compatible with these changes from Blizzard.
	
The current version will remain available via curse as is and if/when Blizzard make any announcements for new Classic SoM or TBC SoM servers, either the new version can be backported to work with those servers or the older version will receive maintenance.
	
Check the Discord server for more informations.
"
(*temporary) = "string expected, got nil"

Lua Error 3/3:
Message: Interface\AddOns\Guildbook\Core.lua:3039: attempt to compare nil with number
Time: Sat Jul 30 15:16:30 2022
Count: 5
Stack: Interface\AddOns\Guildbook\Core.lua:3039: attempt to compare nil with number
[string "@Interface\AddOns\Guildbook\Core.lua"]:3039: in function `?'
[string "@Interface\AddOns\Guildbook\Core.lua"]:2605: in function `ProcessIncomingData'
[string "@Interface\AddOns\Guildbook\Core.lua"]:2590: in function <Interface\AddOns\Guildbook\Core.lua:2589>

Locals: self = <table> {
 sendPlayerCharacterTradeskillRecipes_IsQueued = false
 ProcessIncomingData = <function> defined @Interface\AddOns\Guildbook\Core.lua:2595
 sendPlayerCharacterTradeskillsInfo_IsQueued = false
 UnregisterComm = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SendTradeskillInfoToTargetGUID = <function> defined @Interface\AddOns\Guildbook\Core.lua:2850
 OnGuildbookConfigChanged = <function> defined @Interface\AddOns\Guildbook\Core.lua:2359
 SayHelloBack = <function> defined @Interface\AddOns\Guildbook\Core.lua:2990
 OnCommReceived = <function> defined @Interface\AddOns\Guildbook\Core.lua:2552
 playerCharacterUpdate = <table> {
 }
 SendPrivacyNotice = <function> defined @Interface\AddOns\Guildbook\Core.lua:2668
 OnLFGListingCreated = <function> defined @Interface\AddOns\Guildbook\Core.lua:3206
 OnCharacterTalentsUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:3133
 Transmit = <function> defined @Interface\AddOns\Guildbook\Core.lua:2418
 SendCharacterTradeskillInfo = <function> defined @Interface\AddOns\Guildbook\Core.lua:2813
 RequestCharacterInfo = <function> defined @Interface\AddOns\Guildbook\Core.lua:2703
 GetCallbacksByEvent = <function> defined @Interface\SharedXML\CallbackRegistry.lua:51
 UnregisterEvents = <function> defined @Interface\SharedXML\CallbackRegistry.lua:140
 CheckPrivacyRuleForTargetGUID = <function> defined @Interface\AddOns\Guildbook\Core.lua:2618
 CharacterSpecAndMainChatFilter = <function> defined @Interface\AddOns\Guildbook\Core.lua:2319
 UnregisterAllComm = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 OnCharacterTradeskillsRecipesUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:3100
 OnLoad = <function> defined @Interface\SharedXML\CallbackRegistry.lua:31
 Event = <table> {
 }
 playerCharacterTradeskillRecipesUpdate = <table> {
 }
 playerCharacterTradeskillsInfoUpdate = <table> {
 }
 OnPrivacyNotice = <function> defined @Interface\AddOns\Guildbook\Core.lua:2681
 SendNewsUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:2977
 TellGuildMemberItsTimeToUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:3005
 SayHello = <function> defined @Interface\AddOns\Guildbook\Core.lua:2688
 OnCharacterTradeskillsInfoUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:3116
 OnCharacterInfoRequested = <function> defined @Interface\AddOns\Guildbook\Core.lua:3254
 sendPlayerCharacterTradeskillsInfoQueueTimer = 3
 sendPlayerCharacterUpdates_IsQueued = false
 TriggerEvent = <function> defined @Interface\SharedXML\CallbackRegistry.lua:99
 callbackTables = <table> {
 }
 OnCharacterUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:3179
 RegisterCallback = <function> defined @Interface\SharedXML\CallbackRegistry.lua:72
 SetUndefinedEventsAllowed = <function> defined @Interface\SharedXML\CallbackRegistry.lua:39
 UnregisterCallback = <function> defined @Interface\SharedXML\CallbackRegistry.lua:125
 SendCharacterTalentsInfo = <function> defined @Interface\AddOns\Guildbook\Core.lua:2723
 SendCharacterTradeskillsRecipes = <function> defined @Interface\AddOns\Guildbook\Core.lua:2879
 SendCommMessage = <function> defined @Interface\AddOns\DataStore\libs\AceComm-3.0\AceComm-3.0.lua:87
 DELAY = 2
 sendPlayerCharacterUpdatesQueueTimer = 3
 OnCharacterPaperDollStatsUpdate = <function> defined @Interface\AddOns\Guildbook\Core.lua:3149
 RegisterComm = <

**Comment by Belrand** [comment]
Thanks for the report, I think I see the issue, that's my bad I'll try to fix it ASAP

**Comment by Belrand** [comment]
The issue came from a wrong label in the "Version" of the addon within the .toc file, it should be resolved.

Update as been send to curse and is waiting for approval, if you don't want to download it again, you can simply open the file Guildbook-XXX.toc (where XXX correspond that version of the game you're running Classic or BCC) with a text editor and change the version from `4.9941a` to `4.99411`.

Sorry again for the mistake.

**Comment by MurderOnMyMind7** [comment]
Thank you! I Have no issue just downloading the update when it clears. Thanks SO MUCH for being so quick to resolve this issue. I'm a big fan of this addon and unfortunately this error kept popping up every couple minutes and was driving me nuts. I was forced to disable it. Looking forward to using this addon in WotLK. Have a great weekend :D
