### ISSUE TITLE
Guildbook debugg window

### ISSUE THREAD

**Issue by elfluna666** [stpain/guildbook#108]
Hello,

I've a bug with Guildbook. I've this windows is appear when I connect (with all character). I uninstalled and reinstalled while deleting savedvariable, but the problem persists. I'm not alone with this issue. Can you help me ? Thank you.
![WoWScrnShot_090222_190650](https://user-images.githubusercontent.com/112720571/188204771-971dfcf6-b7cf-47c9-bb12-34efa0f00775.jpg)

**Comment by endomorphine** [comment]
you can fix it yourself if you add at the end of Debugger.lua
`Guildbook.DebuggerWindow:Hide()`

**Comment by Belrand** [comment]
Hello,

Yes this has been reported, stpain forced open it on load for debugging purpose but forgot to remove that when pushing the release. It's been fixed for the next commit or release.

Sorry for the inconvenience

**Comment by elfluna666** [comment]
Thx @endomorphine but I still can't use the addon.
@Belrand : okay I will wait ^^.

**Comment by Belrand** [comment]
FR:
La fenêtre ne devrait pas empêcher l'utilisation de Guildbook, il suffit de la fermer quand on rentre en jeu (si elle ne peut pas être fermée, ça veut dire qu'il y a un soucis dans l'installation)

Si tu ne veux pas attendre, la méthode d'endomorphine marche.

Va dans ton dossier "Guildbook" ( `\World of Warcraft\_classic_\Interface\AddOns\Guildbook` )
Ouvre le fichier `Debugger.lua` via un éditeur de texte (Bloc-notes marche)
Tout au fond du texte, tu rajoutes une lignes avec qu'a écrit endomorphine: `Guildbook.DebuggerWindow:Hide()`
Ce devrait ressembler à ça :
![image](https://user-images.githubusercontent.com/87081225/188223613-039bfbf3-ebe5-4f6c-a8a8-9fd301fca1cf.png)


EN:
The windows doesn't prevent the addon from working it simply needs to be closed every time you log in (if it can't be closed then something went wrong during the installation)

If you cannot wait, endomorphine's fix works

Open "Guildbook" folder ( `\World of Warcraft\_classic_\Interface\AddOns\Guildbook` )
Open "Debugger.lua" file via a text editor (notepad works)
Scroll down to the end of the text, add a new line with what endomorphine has written : `Guildbook.DebuggerWindow:Hide()`
It should look like the screenshot above.

**Comment by elfluna666** [comment]
J'ai utilisé la méthode d'endomorphine mais guildbook ne marche pas.

I used the endomorphine method but guildbook doesn't work.

**Comment by endomorphine** [comment]
it's not mine actually, credit goes to mod author himself, they've posted this fix in discord, I just tried it and it works for removing debug window, yeah

**Comment by Belrand** [comment]
@elfluna666 Tu peux élaborer quand tu dis que l'addone ne marche pas?
L'ajout de la ligne force la fermeture de la fenêtre au lancement du jeu, il ne devrait pas empêcher l'addon de fonctionner

**Comment by elfluna666** [comment]
Quand j'ouvre le panneau Guilde, celui-ci n'est pas remplacé par guildbook.

**Comment by Belrand** [comment]
Oh, ça c'est "normal" : l'addon ayant été complètement retravaillé, cette fonctionnalité n'a pas encore été remise.
Le code est toujours présent, mais n'a pas encore été réactivé.

**Comment by elfluna666** [comment]
Okay mais là il ne fonctionne plus du tout.

**Comment by Belrand** [comment]
Le scan de métier devrait fonctionner (à part Calligraphie qui arrive à la prochaine update)
Les Profils devrait marcher aussi (talents, glyphes, spé, etc)
La fenêtre de guilde modifiée n'est pas encore disponible, le code est toujours présent, **mais** n'est pas encore retravaillé pour la nouvelle version de l'addon et donc ne fonctionne pas.

Jusqu'à présent stpain à prioriser la transition vers la nouvelle version, un bug de fuite de mémoire et l'addition de la calligraphie.
L'addon a du être adapté pour le prépatch, mais tout comme le prépatch a encore besoin de développement pour être entièrement fonctionnel 😉

**Comment by Belrand** [comment]
EN:
Fixed in commit [`885c8f`](https://github.com/stpain/guildbook/commit/885c8f331574d6479efbb265b5ef48062e31ed05) by @stpain  😄 

Debug window is now closed on loading game
Modified Blizz Roster added back in

FR:
La fenêtre debug est maintenant fermée à l'entrée en jeu
La fenêtre de guilde modifié a été rajoutée

**Comment by elfluna666** [comment]
Okay, j'attends de pouvoir le télécharger. Sur Curse, il est toujours en 5.12.
