### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by hillerstorm** [stpain/guildbook#11]
Right now I can only set a main character that's on the same account as my alt. Would be nice with an account-sync feature similar to how TradeSkillMaster does it (you connect two accounts by writing the name of your characters on two accounts simultaneously and the addon establishes a connection).

Or perhaps a simpler way of adding a slash-command to manually set mains? Like `/guildbook main <Name>` and it sets that char to your main.

**Comment by HgAlexx** [comment]
Hello,

Love the recent changes, however I was about to post the same issue, I can no longer set my main char on the second account :(

**Comment by stpain** [comment]
Yes I realised this issue the other day, I was happy with the auto list but as you pount out it only shows from 1 account, I will add something to resolve this.

**Comment by stpain** [comment]
Hi sorry its taken time but i am adding a way to set a main character for multiple accounts. Should be in the next update, thanks
