### ISSUE TITLE
[Bug] Minimap toggle setting is not saved

### ISSUE THREAD

**Issue by Stanzilla** [stpain/guildbook#111]
The setting to show/hide the minimap button is not persisted across sessions.

Looks like the value in the SV is correct, it's just not applied correctly on load. Maybe a race.

**Comment by stpain** [comment]
Ok so the issue was the database key checking code, i was using

`if not x then` and i should have used `if x == nil then` as false can be a valid value

As it was the value was being reset as it regarded false as not existing.

Seems to be working now, thanks.
