### ISSUE TITLE
missing jc patterns

### ISSUE THREAD

**Issue by wonwon0** [stpain/guildbook#115]
when i search i cannot find

https://www.wowhead.com/item=40052/deadly-monarch-topaz
https://www.wowhead.com/item=40055/deft-monarch-topaz

**Comment by Belrand** [comment]
Thanks for the report!

I created a new [thread](https://github.com/stpain/guildbook/issues/116)  to better manage the issue and added those to the list of "known missing" items

I'm closing this issue to redirect people towards the new thread
