### ISSUE TITLE
Enchanting profession does not populate guild recipes or characters.

### ISSUE THREAD

**Issue by physixtential** [stpain/guildbook#17]
I got a bunch of people in my guild to install this yesterday mainly for the profession tracking, but the enchanting profession doesn't fill with recipes or characters. All the other professions work. I can see recipes and click on them for who has them. We have a ton of enchanters, including myself, and we all opened our profession windows after install (seems to be required?).

**Comment by stpain** [comment]
this should have been fixed in 4.7
