### ISSUE TITLE
Profession specialization info

### ISSUE THREAD

**Issue by Bonkeybee** [stpain/guildbook#44]
As always, love the addon and the hard work you put into it. With TBC, it would be very useful for Guildbook to have indicators on what specializations people are when looking up recipes/crafters.

Sure, someone is available to craft my Flask of Mighty Restoration, but which of them are specialized in it?

**Comment by stpain** [comment]
yes this is on my list, thanks for the reminder

**Comment by stpain** [comment]
hopefully you've seen in the roster tooltip and the tradeskill buttons tooltip i have added the prof spec info, will look at further ways to make this easier to view.
