### ISSUE TITLE
Cant see my own Recipes 

### ISSUE THREAD

**Issue by emanueol** [stpain/guildbook#47]
Gi,

Just instaled this addon that seems interesting, but when I open:
Right click minimap icon Guildbook > Professions > Engineer

I see a never ending animated circle, and dont see my Engineering recipes (Im max 300 Engineer).

Any suggestion ? I found this addon could be very usefull, but need to be sure its working at it core.

Thanks,
~ Budha ~

**Comment by Belrand** [comment]
Hello,

It seems you haven't properly scanned your own professions.
To do so, you must open your profession window (this will scan all your recipes for that profession); once a profession is scanned Guildbook will send the data to all your online guild member (with the addon installed) every time you log in.
However the scanning process must first be executed for every profession individually

Cheers,

**Comment by emanueol** [comment]
here the steps took:
open big professions window with list of all professions in wow on left >
then i left clicked on engineering since i have that profession and max
level 300 > the i see animation of big circle on right side but it doesn't
stop neither anything as appears.

Are these steps ok or im doing something wrong?
2. Im playing WoW Classic Burning Crusade, does addon supports TBC classic ?

Thanks and Kind regards,
Budha

**Comment by Belrand** [comment]
The addon is indeed developed for TBC Classic

You do not need to have the Guildbook frame open to scan anything. 
Once the scanning is done a message should show in the chat (if you have checked the options) displaying "Found X recipes, estimated duration Y Sec", this means the scanning process for one profession is done, if no more data is being received by the addon (no other online guild member) another message displaying "all tradeskills recipes processed, tool Y Sec"

You can then click on the profession in the Tradeskills frame and the recipes should show:
https://user-images.githubusercontent.com/87081225/128686008-cd4fc52c-195e-4bd1-939a-12ee4a52e4d6.mp4
(sorry for the quality it's best I could on short notice)

If it still doesn't, enable the "Debug" Options and see if it does send/recieve data when you open a Profession.

Hope this help,
Cheers

**Comment by emanueol** [comment]
I see in you gif that normal game professions window also open, is that
necessary for addon to be able to scan ?


Thanks and Kind regards,
Emanuel de Oliveira

**Comment by Belrand** [comment]
Yes, as I said earliear this is necessary for the scanning process to occur, I'm sorry if I wasn't clear enough

You can find more informations about the Addon by clicking the "?" button in top right corner

**Comment by stpain** [comment]
i am currently trialing a small scan set up when you log in, havent yet settled on the exact ux for it but this will solve the issues. alternatively the addon scan whenever you open a profession.

**Comment by emanueol** [comment]
Thanks for your support ;)
