### ISSUE TITLE
Privacy setting 'none' isn't saved

### ISSUE THREAD

**Issue by kazso** [stpain/guildbook#48]
When I set any of the privacy settings to 'none', it won't be saved. Higher privacy levels are saved.
If I don't want to share something, I have to manually set it to 'none' after login or UI reload.

**Comment by stpain** [comment]
Hi, i think i have tracked down this bug, the addon checks that the privacy ranks exists, as in the rank hasnt been removed since your last session. I didnt add a check for the nobody rank, this is fixed for the next update.
