### ISSUE TITLE
Characters' recipes not showing up in professions tab

### ISSUE THREAD

**Issue by ashobwow** [stpain/guildbook#52]
I'm having problems seeing entire recipe sets from characters when I click on the profession from the professions tab. I know that the addon has stored the professions data because when I click on the profession icon for a specific person from the roster I can see their correct professions list. But I am running into problems when more than one person has the profession. The main list from the professions tab will only show recipes that one of the people has, not the combined list from everyone. We don't have widespread adoption in the guild right now and only have a max of two people with any profession with this addon, so I can't say if it's just showing one person's list or everybody's except for one person.

For example:
I click my own leatherworking icon in roster, see nethercobra leg armor on my list.
I click the LW in the professions tab, then only see recipes that a different guild mate has and no nethercobra or any others of mine.
I can search specifically for nethercobra leg armor in the search feature and click on it once I see it there, and it will just scroll through the whole LW profession and not find it.

If I do click on a recipe from the professions tab I can see that I have it, but if the other guildmate doesn't have it then I can only see it by clicking my LW icon on the roster.

This is not limited to only professions that one of my characters has. I am having the same issue with JC from two other guildmates that both have that profession.

**Comment by virtualbjorn** [comment]
And to add with that, Characters are not showing up on the characters listing on the Recipes UI.
For example my guildie have an Alchemist along with another guild member, I could see the guild recipes but the ones who have Alchemy is not listed on the Characters Listing on the Recipes UI.

**Comment by ashobwow** [comment]
Issue seems to be resolved for me with a recent update, thanks
