### ISSUE TITLE
[Request] Filter Recipe by Category

### ISSUE THREAD

**Issue by virtualbjorn** [stpain/guildbook#59]
The recipe listing is uncategorized right now and having the requested filter will help the user find what they need faster.

![image](https://user-images.githubusercontent.com/19782129/132242743-0628171e-8a88-4af9-ab7b-4ee00d6a738c.png)

**Comment by stpain** [comment]
What category are you referring to, the tradeskill spec (mooncloth/spellcloth etc) or a particular slot an item equips in (hands/boots).

The search bar at the top will find a lot of things, although it requires the addon to process data from the server first so needs a few mins to get set up.

**Comment by virtualbjorn** [comment]
Maybe like a grouping of recipes. E.g Bag, Mail, Plate, Misc, Parts

Just the common category you see for the items. It doesn't have be per slot I think.

**Comment by virtualbjorn** [comment]
Anyway, its great to find this addon! Really helpful.

**Comment by stpain** [comment]
filterign by inventory slot and also consumable type have now been added
