### ISSUE TITLE
Professions tooltip error when mouseover unit

### ISSUE THREAD

**Issue by Bonkeybee** [stpain/guildbook#6]
2x Guildbook\Guildbook_Core.lua:341: attempt to index field '?' (a nil value)
Guildbook\Guildbook_Core.lua:341: in function <Guildbook\Guildbook_Core.lua:314>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0-9.lua:95: in function <...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:87>
[C]: ?

Locals:
self = GameTooltip {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 hasMoney = 1
 comparing = false
 Hide = <function> defined =[C]:-1
 SetCraftItem = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetQuestLogRewardSpell = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetShapeshift = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 ClearLines = <function> defined =[C]:-1
 LibExtraTipLeft = <table> {
 }
 ARKTTD = <table> {
 }
 Show = <function> defined =[C]:-1
 __hasEPGPTooltip = false
 SetPetAction = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 default = 1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 TopOverlay = <unnamed> {
 }
 LibExtraTipRight = <table> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 ttGradient = <unnamed> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 FadeOut = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetTradePlayerItem = <function> defined =[C]:-1
 SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
 SetSendMailItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 updateTooltip = 0.016000
 SetInventoryItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 ttIcon = <unnamed> {
 }
 SetUnitBuff = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
_ = "Kalanianaole"
unit = "mouseover"
guid = "Player-4648-002C2C0F"
guildName = "Valhalla"
character = <table> {
 MainSpec = "-"
 Name = "Kalanianaole"
 Talents = <table> {
 }
 OffSpec = "-"
 Class = "MAGE"
 Level = 60
 PaperDollStats = <table> {
 }
}
r = 0.250000
g = 0.780000
b = 0.920000
(*temporary) = <function> defined =[C]:-1
(*temporary) = GameTooltip {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 hasMoney = 1
 comparing = false
 Hide = <function> defined =[C]:-1
 SetCraftItem = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetQuestLogRewardSpell = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetShapeshift = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 ClearLines = <function> defined =[C]:-1
 LibExtraTipLeft = <table> {
 }
 ARKTTD = <table> {
 }
 Show = <function> defined =[C]:-1
 __hasEPGPTooltip = false
 SetPetAction = <function> defined @BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:419
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 default = 1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 TopOverlay = <unnamed> {
 }
 LibExtraTipRight = <table> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 ttGradient = <unnamed> {
 }
 SetMerchantItem = <function

**Comment by Bonkeybee** [comment]
![image](https://user-images.githubusercontent.com/9619823/116726259-a606de80-a9a8-11eb-98ad-4bcf671cb0dc.png)

**Comment by Bonkeybee** [comment]
Turning off the professions check box for the tooltip info "fixes" the error, but obviously then profession info wont be shown.

**Comment by stpain** [comment]
Hmm, I haven't looked at this addon for a while now.

Looking at line 341 it's trying to set some text and a texture string. The line above though it checks if the value exists.

Is this definitely a Guildbook error, what happens if you deactivate other tooltip addons or addons that modify the tooltip, I might have to look at some compatability issues.

**Comment by Bonkeybee** [comment]
For reference I was using the TipTac addon. I haven't been able to test if this error only occurs with TipTac or not yet. I'll get back to you.
