### ISSUE TITLE
Calendar Scrollbar not Working

### ISSUE THREAD

**Issue by Hamsterli86** [stpain/guildbook#63]
the Calendar Scrollbar shows only the first 15 Entrys. When I´m scroll down there ist only a black page.
all other addons are disabled.
![image](https://user-images.githubusercontent.com/90343230/132551936-cdfeb7e2-bbc2-4c64-bb86-be8d3c2370d0.png)
![image](https://user-images.githubusercontent.com/90343230/132551981-4aa881e4-0e62-4255-9ea7-506ec64647df.png)

**Comment by stpain** [comment]
hmmm, i will look at getting this updated to a newer listview system

**Comment by stpain** [comment]
this has now been updated to the new listview widget
