### ISSUE TITLE
Add indicator for recipe search if character is online or not

### ISSUE THREAD

**Issue by Bonkeybee** [stpain/guildbook#7]
In the profile search for recipes, can we get a feature enhancement to add some kind of indicator (perhaps color the text) to indicate if the character who has the recipe is online or not? At the moment, all members who have the recipe is returned.

![image](https://user-images.githubusercontent.com/9619823/117324985-eefddd80-ae55-11eb-934c-f9aab34ab25c.png)

**Comment by Bonkeybee** [comment]
I would recommend coloring the text of offline recipe holders a darker grey, like in the roster panel

![image](https://user-images.githubusercontent.com/9619823/117325231-21a7d600-ae56-11eb-9755-6b4b50c3e2c6.png)

**Comment by Bonkeybee** [comment]
Some background, I'm the guildmaster of a large guild (900+ members) and we **really** want to adopt this addon widespread instead of using discord channels to list our recipes. Guildbook is obviously perfect for this, but not being able to tell if the recipe holder is online or not limits this panels usefulness, especially when this list will contain hundreds of recipe holders.

**Comment by stpain** [comment]
Hi, this was something i had intended to add, i'm currently working on a retail addon but will be back to classic as soon as i can get into a ptr (i was late for a beta key so been a bit stuck for a while).

I will take a look at the code later to see if there is a quick fix to add this functionality and will post an update if so.

Glad you are enjoying it, i've actually been thinking about the future of Guildbook going forward, tbc and then wrath will introduce guild banks and calendars, so i'm thinking of just beefing up the trade/recipe section and the character profiles.

Would you have any opinions on this sort of change.

**Comment by stpain** [comment]
![image](https://user-images.githubusercontent.com/47498931/117360215-695b4b80-aeb0-11eb-8251-644d28275a4d.png)

I've setup the checkbox to show if the member is online, i'm going to go through the code at some point as it feels slow.

**Comment by stpain** [comment]
sent an update, added a search button as the function is laggy when using the text changed event

**Comment by Bonkeybee** [comment]
@stpain thanks for the quick update! It works perfectly. And yes, our guild personally doesn't use the calendar feature (everything is scheduled in discord anyways) and with the guild banks in TBC it's likely that functionality wont be used by anyone except Classic Era guilds (if you plan on supporting them).

**Comment by stpain** [comment]
I've been stuck with just 1 monitor for classic so having the in game calendar was a huge help for me. Plus I find discord bots terrible for organising events, they're ok if there is only 1 event but as soon as that bot gets into multiple channels with several weeks scheduled ahead and it's a labyrinth of messages where the date is never the biggest font.
Anyways ramble over, do shout out about anything else you think would be good, used, not used etc.

**Comment by Bonkeybee** [comment]
My only other suggestion would be to sort the online players at the top of the search results list.

![image](https://user-images.githubusercontent.com/9619823/117380277-f4cbe100-ae9e-11eb-8ce6-3b9fa64949ee.png)

And we actually have our events organized as separate channels, with the date and event title as the channel name:

![image](https://user-images.githubusercontent.com/9619823/117380347-1c22ae00-ae9f-11eb-833c-b29b8068a88b.png)

**Comment by stpain** [comment]
Oh that's a good idea.

I'm currently working on an update for Guildbook with a much better ui/ux for guild tradeskill.
![gb-tradeskill.gif](https://user-images.githubusercontent.com/47498931/117656196-f55ec300-b18f-11eb-93bc-b060f4f1d534.gif)
So with this, you select the profession, itll show all recipes from all guild members, then selected a recipe will display who can make it. This is also sorted to show online players first.

Potentially moving some bits out of the guild frame ui.

Will close this issue however as I feel its resolved, any feedback is welcome on the new idea though, thanks.
