### ISSUE TITLE
Update 4.981 broke gathermate2

### ISSUE THREAD

**Issue by luitzifa** [stpain/guildbook#81]
Hi,

it sounds quite strange but the last update broke gathermate2.
gathermates creates "waypoints" on map and minimap when you loot from herbal or mining nodes.
Since last guildbook update 4.981 those waypoints disapper after mage teleport or hearthstone teleport.

I don't get a LUA error, it just doesn't work.
I made a video to show you: https://www.youtube.com/watch?v=8vfwl2_9JYA

**Comment by stpain** [comment]
Hi,

I would say with about 99% certainty that this isnt a guildbook issue, guildbook doesnt touch the minimap nor does it touch the HBD lib required for minimap icons etc

I have however noticed when i go to skettis the nodes often disappear and also soemtimes just going from zone to zone.

I will keep a note of this and if any should show up as being an issue that is something i need to resolve then i will of course take action.

**Comment by Belrand** [comment]
Hey there,

As stpain said, there shouldn't be any conflict between the two addons, nevertheless if there were, it would 100% display a Lua error

Are you sure your interface is configured to display Lua errors? With no interface addon, they should be hidden by default.
Could you type in chat
> /console scriptErrors 1
and see if anything shows after you teleport/hearthstone?

**Comment by luitzifa** [comment]
Sorry, no Lua Errors displayed with `/console scriptErrors 1`

I installed 4.973 and the issue was gone. Reinstalled 4.981 and issue is back.

**Comment by luitzifa** [comment]
I know that it sound really impossible, even for a noob like me. Thats why i made the video :-/

**Comment by luitzifa** [comment]
OK, now, just to be sure that there is some kind of incompatibilty:

1. removed WTF, Cache and Interface
2. Started wow-tbc. 
3. Exited game.
4. Install Guildbook, Gathermate2 and Gathermate2 data
5. Started the Game
6. pasted `/console scriptErrors 1` into the chat
7. reloaded with `/reload`
8. Imported the gathermate data
9. Nodes were visible
10. teleported to theramore
11. Node were invisible again

**Comment by Belrand** [comment]
This is a long shot, but could you try with Guildbook database installed as well? 
( https://www.curseforge.com/wow/addons/guildbook_tsdb )

@stpain Do you think Guildbook could *somehow* get confused and try to call the wrong databse?

**Comment by stpain** [comment]
well i have both addons running and have just done the skettis egg bomb daily and the cooking daily for mana berries, that involves several zones and at all times the minimap was showing gathermate node icons

feel free to do a ctrl+f in any guildbook file for either Gathermate or HBD (HereBeDragons lib which does the minimap icons), guildbook doesnt touch anything to do with it.

**Comment by luitzifa** [comment]
Installed guildbook_tsdb but no change.

**Comment by luitzifa** [comment]
Flying from one zone to another works for me.

**Comment by stpain** [comment]
just to add to this, i was in skettis but got logged out due to afk timer

logged back in and none of my gathermate nodes show up, anywhere, flew back to shat (no portals or HS) and still no nodes showing

**Comment by luitzifa** [comment]
Today i notized that gathermate2 has the option to show the node only when you have the profession, which is default i think, or always or when tracking or never. So when i just switch to "always", the nodes appear.

I'm guessing that somehow in some situations gathermate2 is unable to find out that i have herbalism and this is caused by some kind of interference with guildbook.

**Comment by stpain** [comment]
hmmm, i dont have the kowledge to 100% rule it out, however as ive stated before there is zero mention or reference or variable or pointer that interacts with Gathermate2 - so the chance of guildbook being able to modify a value ro setting of athermate2 is incredibly slim

**Comment by luitzifa** [comment]
Further investigation into gathermate2 show they use https://wowpedia.fandom.com/wiki/API_GetSkillLineInfo to get info about professions. The return of that is different when using guildbook.

**Comment by luitzifa** [comment]
I think it's because you collapse it

**Comment by stpain** [comment]
aye it could be, it will return nothing if the header is colapsed

**Comment by luitzifa** [comment]
I don't quite understand why it is collapsed with guildbook. The code of guildbook suggests it restores the initial state.

**Comment by stpain** [comment]
well thats the idea, could be something beyond my understanding, for example the blizz code for the interfaces does something i dont know about.

i have commented this out for now and will use the spellbook method and look for a way to grab prof levels

**Comment by luitzifa** [comment]
i ran
`/run for i = 1, GetNumSkillLines() do local skill, isHeader, isExpanded, level, _, _, _, _, _, _, _, _, _ = GetSkillLineInfo(i); if isExpanded then ExpandSkillHeader(i) else CollapseSkillHeader(i) end end`
in wow and it always collapses.

**Comment by luitzifa** [comment]
So the problem is:
The isExpanded of the for example alchemy is always nil because its not a header. The code trys to restore this state and actually collapses the header of alchemy which is "professions".

**Comment by stpain** [comment]
ah i see what you mean, i've added a different method to get the skill level which could mean removing a chunk of the skill  lines stuff, pushed to git but not published as update

**Comment by luitzifa** [comment]
I can confirm that this Issue is solved in current master branch

**Comment by stpain** [comment]
hmm, didnt get that myself, are you on classic or tbc? its an easy fix but just curious - its a blizz global name for something

**Comment by luitzifa** [comment]
i'm on tbc
I can reproduce this error by cooking something.

**Comment by stpain** [comment]
Ah, I didn't specifically check for cooking as I assumed it was under crafting. Basically from what I've discovered they have tradeskill and craft which covers professions and cooking and even pet training etc.

Most professions fall under tradeskill except enchanting which uses crafting, so I'll have to check the name for the ui element used for cooking.

Thanks

**Comment by stpain** [comment]
mmm ok the cooking ui uses the tradeskill named widgets so ive just added an extra check for the object name

**Comment by luitzifa** [comment]
i guess this can be closed now.
