### ISSUE TITLE
Enchanting recipe scanning is broken after code tidy commit (version 4.9832)

### ISSUE THREAD

**Issue by xbend** [stpain/guildbook#93]
@stpain 
Hey, I was investigating an issue with my guildbook not syncing new enchanting recipes after 4.9832.
According to my debugging, the bug was introduced with https://github.com/stpain/guildbook/commit/40fb2bb59be0d03ae6c4565f980a59207e9a7b5a

[Core.lua Line: 1515](https://github.com/stpain/guildbook/blob/d2c4aa02c50bbbe4e782e9b5387287c7a7969e4a/Core.lua#L1515)
the condition `if not englishProf then` was mistakenly rewritten to `if englishProf ~= false`.
So if `englishProf` anything but `false` (like, for example "Enchanting") this new condition will be true ("Enchanting" is not equal to false) and the recipe scanning function will `return`.

Simply change that line to `if englishProf == false` and recipe scanning is back to normal.

I can PR the change myself if required.

**Comment by stpain** [comment]
![image](https://user-images.githubusercontent.com/47498931/153093130-3a996e0f-8bf7-41e2-a179-78d93456ce5b.png)

i think i may have fixed this with my latest working version, th code looks different to last commit

**Comment by xbend** [comment]
The issue I was pointing out is a different code section. Function `function Character:ScanEnchantingRecipes()`
![Core lua](https://user-images.githubusercontent.com/7847377/153183063-a892db1f-c1d0-45eb-ae08-c6387faafb49.png)

Maybe your working code version modified it, but I was basing this issue on Core.lua in master branch.

**Comment by stpain** [comment]
ah enchanting, that old nasty sorceress, the enchanting function should look almost the same as the other but uses the craft frame etc, will look into it in a mo

**Comment by xbend** [comment]
@stpain 
Latest build fixed the issue (this commit preciselly: https://github.com/stpain/guildbook/commit/b3e1b45797d31f6178999b4b76db4749a3d6ac49)

Cheers!
